### ISSUE TITLE
After Spring Cleaning, chat does not work

### ISSUE THREAD

**Issue by Ranguvar** [loopuleasa/Dota2-TheCore-Config-Engine#137]
say and say_team still work in console..

**Comment by nickcorona** [comment]
+1 Chat does not work.

**Comment by nickcorona** [comment]
https://www.reddit.com/r/DotA2/comments/4buau7/chat_not_working_in_spring_cleaning/

**Comment by jaccarmac** [comment]
@loopuleasa has been good about showing up when breaking bugs reared their heads in the past, so I imagine they will continue to do so. That said, the engine still has a few quirks that need to be worked out. I've contributed before but recently have been too lazy to fix anything since nothing was fully broken. We may need to organize a Spring Cleaning of our own; I propose a milestone of some kind. I'll gladly take a look through and try to fix things if we identify problem areas.

/rant

All right, back on topic: Several features in the client seem downright broken at the moment, and the syntax for commands has gotten more restrictive (Pimpmuckl detailed that little bug). Some issues may be fixed with further client updates, while others may have to be fixed by combing the config.

**Comment by aspalmer** [comment]
Use the ingame bind and -

you have to comment out 2 lines in dota2_gameplay_mode.cfg:
bind "KP_ENTER" "say"
bind "ENTER" "say

and comment out all the unbindall's from:
dota2_keybind_default and the 3 XXXX_pressed ones

**Comment by Acerecon** [comment]
@aspalmer Has this been successful for you? I commented out those two lines but chat still breaks as soon as i press space bar.

**Comment by Sembrani** [comment]
Unfortunately I won't have a chance to go through the config for at least a week due to university commitments, however after that I will make sure everything gets updated to a working state, and move on to integrate the new features from the spring cleaning update in the config, provided @loopuleasa or someone else doesn't get to it first.

**Comment by Acerecon** [comment]
@Sembrani I've just finished all my college tests and have no problem parsing through it all I just don't exactly know how to know what needs changing. Do you know of any resources to learn about this stuff?

**Comment by aspalmer** [comment]
@Acerecon You need to uncomment the 4 instances of unbind all. It's in dota2_keybind_default and the 3 XXXX_pressed ones

**Comment by Acerecon** [comment]
@aspalmer Yup I did that as well. The image is in all four pressed ones.
![image](https://cloud.githubusercontent.com/assets/18063793/14038468/5a80964c-f20e-11e5-9aa4-487ca3e4e5ec.png)

**Comment by Acerecon** [comment]
And just to be 100% clear these are the lines you said yuo also commented out in default? 

![image](https://cloud.githubusercontent.com/assets/18063793/14038485/ba98c5cc-f20e-11e5-9918-63ea04aa1a98.png)

**Comment by 0x4C** [comment]
I'm not comfortable with removing all occurrences of unbindall as a workaround due to the unintended consequences it may lead to.

unbindall is used at the beginning of each modifiers list of keybindings in order to prevent overlap from one set of bindings onto another.

For example lets say you use SPACE+F4 as your activate glyph key, and perhaps you use ALT+F4 as a binding to perform some other action, lets say the "gameui_activate" command which returns you to the main Dota menu (same as clicking the top left button in the game UI).

If you do not use the F4 naked/without a modifier as a bound key in this hypothetical example then if you accidentally press F4 without any modifier key you'll either unintentionally activate the glyph, or unintentionally return to the main menu, depending on whether you have more recently used an alt or space modifier.

Likewise any other key that you have bound as a modifier but not as an unmodified key will execute unintended commands if pressed without a modifier.

You could as a workaround replace the unbindall command with a manual list of every key you use whatsoever in the config that you wish to be unbound e.g.

unbind F1
unbind F2
...
unbind Q
unbind W
ad nauseum in order to preserve the original game UI binding of the enter key to the say command, but that's doesn't seem to be a very practical solution. Although we may be stuck with it if one does not want to be caught out by unintended bindings.

I suspect that the problem with binding a key to the say command is an unintended change from the spring cleaning patch and may potentially be fixed at Valves end, although given the amount of issues introduced by the patch it is possible this is a low priority and may be overlooked or take a while.

So while removing unbindall may be a workaround, it doesn't seem to me a proper fix and should be used with caution.

**Comment by aspalmer** [comment]
I agree, it's not a fix. But it was the fastest way to make my dota playable. I think they will fix the binding stuff in one of the hotfixes in the next day or two though and I can revert my local changes.

**Comment by Acerecon** [comment]
@aspalmer You ever try to see where our differences lie? I can't seem to get your quick fix to work.

**Comment by Sembrani** [comment]
I think the reason commenting out the first "unbindall" works, is so that the original DotA keybind ends up being used.

@Acerecon, if you want to learn, the fastest way is just to read through what is already there, and try to figure out what each line does. The biggest issue with the config right now is the fact that having " " around the bound command no longer works properly. I hope this isn't the case for aliases, though I haven't checked yet.

If someone wants to, just remove all the quotes from around bound commands, so
`bind "key" "COMMAND"`
becomes
`bind "key" COMMAND`, that would likely be the fastest way to get most things working again.

**Comment by loopuleasa** [comment]
I will get on it asap when I get home.

I anticipated something like this.

**Comment by dodekeract** [comment]
@Sembrani it can't be the quotes, these manta-generated keybinds work for me:

````
bind "KP_0" "say_team no"
bind "KP_1" "say_team yes"
bind "KP_2" "chatwheel_say 59"
bind "KP_3" "chatwheel_say 81"
bind "KP_4" "chatwheel_say 75"
bind "KP_5" "chatwheel_say 76"
bind "KP_6" "chatwheel_say 82"
bind "KP_7" "say > That just happened."
bind "KP_8" "chatwheel_say 53"
bind "KP_9" "chatwheel_say 85"
bind "F11" "exec autoexec.cfg"
````

Maybe the quotes are only valid, when there actually is a space/colon, which requires them?

**Comment by Sembrani** [comment]
I suppose that is possible... Makes it a bit painful though.

**Comment by dodekeract** [comment]
Also I think I found a solution on how to avoid `unbindall`, it's not a lot of work for Manta, since it's computer-generated but would be for TheCore. Beware though, because it looks like cancer-code.

````
// # Unloader:
alias custom_unload "custom_unload_0; custom_unload_1; custom_unload_2; custom_unload_3; custom_unload_4; custom_unload_5; custom_unload_6; custom_unload_7; custom_unload_8; custom_unload_9; custom_unload_10"
alias custom_unload_0 "unbind 1; unbind 2; unbind 3; unbind 4; unbind 5"
[...]
alias custom_unload_10 "unbind F11"
````

The reason I had to split it into parts is that there is a maximum command length.

**Comment by dodekeract** [comment]
Are `dota_camera_set_lookatpos` calls broken too?

**Comment by jaccarmac** [comment]
https://twitter.com/PimpmuckL/status/713147482285469699

`bind` is unchanged. It's the other commands where quotes get wonky.

**Comment by loopuleasa** [comment]
apparently I won't be making the fixes today, maybe tomorrow

**Comment by Tabby-** [comment]
The latest patch fixed this issue for me.

**Comment by Enf0** [comment]
Can confirm it's fixed.

**Comment by loopuleasa** [comment]
Nice, it was apparently a general bug.

Only thing I notice now is middle mouse camera grip not working.

**Comment by AetherV** [comment]
@loopuleasa Check my pull: it should fix that plus partially fix the autoattack, assuming that was not patched as well.

**Comment by loopuleasa** [comment]
Tested both of them, they do not work currently.
Will review your pull and recheck afterwards.

**Comment by AetherV** [comment]
@loopuleasa Strange they worked for me yesterday, I'll try today since I haven't tried on the patch yet.

**Comment by loopuleasa** [comment]
I mean, tested it without the pull.
Didn't test your changes yet.

**Comment by loopuleasa** [comment]
Everything seems to be working fine.
Thanks everyone.

**Comment by crimsonvspurple** [comment]
@loopuleasa , how did you fix the chat issue?

**Comment by AetherV** [comment]
Valve patched it. Some bug on their end, where it wouldn't let you bind the say command.

**Comment by dodekeract** [comment]
@loopuleasa can't this be closed?

**Comment by AetherV** [comment]
Should be long closed, after all Valve fixed the bug. @Ranguvar or @loopuleasa should close this as it is a non-issue.
