### ISSUE TITLE
modifier/quickcast issue

### ISSUE THREAD

**Issue by lolnej7** [loopuleasa/Dota2-TheCore-Config-Engine#148]
since today i have strange issues with this config set.
quickcast isnt working, well it is, but as soon as i use some modifier command ( alt or space ) quickcast wont work anymore. after restarting dota it works, till i use some modifier command, exec autoexec wont help enabling quickcast/modifing keys in options wont work aswell. using german layout.
also getting this "yellow lines" in the console since today http://imgur.com/LQMMo1Y
  //e  also after i joined a test game, used 1quickcast then used a modified keypress  http://imgur.com/ipSO91f

**Comment by Kaschmiri** [comment]
This actually sums up my problem (one of the previous issues)- I guess I just didn't realize from what point on quickcast was broken.

**Comment by AetherV** [comment]
Wait why are you using core files for loops config. The core is for creating your own config. If you want to use the one loop made, use his one. And kaschmiri, still haven't managed to patch the German one, I think it's my lack of understanding of how the button next to one works.

**Comment by AetherV** [comment]
Current steps what should (I repeat should) work:

1) backup your config
2) download the config from github 
3) use loops config for qwerty keyboards
3.1) if you are using qwertz check bind keys based on keyboard position

**Comment by Kaschmiri** [comment]
Thanks. I'm gonna try that during the next days. Since I have limited experience with this, I don't know whether it will yield any merit, though.

**Comment by Kaschmiri** [comment]
@AetherV
@lolnej7
Okay. I am getting confused now. 
For the last week, I was using standard keybinds, since the described problems with the modifier keys made it impossible to use the keyfile.
Based on the input here, I today decided to try following the steps AetherV described. I unbound my keys, and installed loops keyfile (just as I did last weekend, after the German version had stopped working and the described error occured).
For some reason, I decided to try out stuff first. Now, I still get the yellow lines that I (and lolnej7 above) have posted screenshots of. 
However, alt- and spacebar modifiers are working fine, now. 
Again, as written in my other post, the only thing that I did so far was changing the modifier key in the \SteamApps\common\dota 2 beta\game\dota\cfg\autoexec to suit a German keyboard by chaning the line

>dota_remap_alt_key "CARET"
to
>dota_remap_alt_key "CARET"

All abilities and items now seem to work with qick/alt-> self/space->normalcast.
I am currently checking the functionality of the other keybinds. I will update this reply.

**Comment by AetherV** [comment]
Alright okay, so if that is working that is good. The yellow stuff is simply a flaw with dota. Prior to Spring Cleaning, you could write the commands in that format, now they want the commands without the `""`. Should be a rather easy fix though, not sure how much relevance it makes, but I have not have the triggers playing any significant role with my config right now.


BTW: @Kaschmiri Did the config work prior to you changing:

> dota_remap_alt_key "´"
> to
> dota_remap_alt_key "CARET"

Or did it only work once that occured

**Comment by dodekeract** [comment]
Also die you change your quick cast setting to "on release"? Manta currently has an issue where someone claims that causes quick cast to no longer work.

**Comment by Kaschmiri** [comment]
@AertherV I didn't check that. I wasn't expecting anything to work without undergoing step 3.1) in your list. Some of the dota updates released during the last week must have fixed stuff.
I can test this tonight, though.
@dodekeract in a quick test in a botgame I had the feeling everything would work. I could use all spells and a variety of items on quick/selfcast. During the last week, I couldn't use any of that, and quickcast for items was very weird even with standard ingame keybindings.

I can do more testing tonight or maybe tomorrow, if you want me to.

Since I am now in a new reply, anyway: All other keys have worked for me- the English version of Loops files seem to provide full functionality for me. 
One exception: jump to courier (space +F2) does nothing, double tapping F2 jumps to courier.

The only key that I had assigned ingame was the console to - on the keypad, and I didn't check action/taunt items.

**Comment by lolnej7** [comment]
sry 4 spam thread, my issue was fixed.
a m8 on other ip/pc used my acc and changed cfg, i had to delte steam cloud cfg and upload 0 byte files to it so it resets.
after that i just repasted the german kb layout files to \cfg works now.
sorry my issue wasnt related to ur cfg set

**Comment by dodekeract** [comment]
Why didn't you close the issue then?

**Comment by lolnej7** [comment]
how? sry

**Comment by dodekeract** [comment]
Just click "Close Issue" below. And your issue isn't related to the project, even if there are people with similar issues a proper issue for this repository would be to add something to the FAQ to prevent this. Or add this feature/whatever.

**Comment by lolnej7** [comment]
ok im sorry, mit not often postin stuff on github
