### ISSUE TITLE
Middle Mouse Bug Fix

### ISSUE THREAD

**Issue by AetherV** [loopuleasa/Dota2-TheCore-Config-Engine#150]
Note in advance: This is a bug fix that includes a solutions. I can't make a pull request because my computer hates PNG files and actively tries to corrupt them at any chance. 

Bug: 
Drag scroll does not release

Reproduction:

1. Press Mouse3 
2. Press Alt (and Space and Alt+Space)
3. Release Mouse3
4. Release Alt (Optional)
5. Now you are stuck in Mouse Drag until Mouse3 is pressed again

Fix:
Add 
`//Mouse3 Bind`
`bind mouse3 +cameragrip`

to

- dota2_keybinds_space_pressed.cfg
- dota2_keybinds_alt_space_pressed.cfg
- dota2_keybinds_alt_pressed.cfg

**After** the unbindall (simplest would be right at the end)

Can someone please make this into a pull request, as I can't without breaking the Keyboard Images 

Edit:
Also fixed inability to use Mouse3 while Alt, Space and Alt+Space are pressed.

**Comment by dodekeract** [comment]
You can actually make a pull request without breaking them. Just use the Git shell (or bash) and enter the following commands:

git clone https://github.com/username/repository
cd repository
*make your changes*
git add filename-you-changed
git commit -m "commit message"
git push

Then create the pull-request from your fork.

**Comment by AetherV** [comment]
The problem is my fork is all messed up, mostly my fault. Played around a bit too much. For some reason the Keyboard Images always are broken, like cannot open corrupted broken. Can't explain that, but whenever I pushed an update to my own fork, they wouldn't work. Also I'm using the Github app and not the shell (kinda too lazy to learn that right now).

**Comment by dodekeract** [comment]
If your fork is all messed up anyway, just delete it and re-fork.

**Comment by AetherV** [comment]
Been there, done that. Computer still corrupts the PNG files for no apparent reason. I am planning to reinstall windows anyways during my summer break, so I'm gonna live with that problem until then. 

Anyhow, I'm going to try it regardless, who knows, might work. Just thought I could post this here in the event that I can't fix it myself. Its better than leaving the bug in the wild without a fix.

**Comment by dodekeract** [comment]
You can chose which files to add to a commit, even in the GUI.

**Comment by AetherV** [comment]
Seems to work, thanks for the help. Now just to fix the PNG's, its messing with my OCD...

**Comment by dodekeract** [comment]
@AetherV Does this look similar to your issue? http://stackoverflow.com/questions/19411981/images-corrupt-after-git-push

If yes, then I guess it's the recent CRLF change someone pushed to this repo. I think it's working fine for me since I'm on Unix but you're on Windows.

**Comment by dodekeract** [comment]
@Sembrani I think you should revert removing that `.png binary` thing from `.gitattributes`, I think this is causing problems here.

**Comment by AetherV** [comment]
Ehm @dodekeract, what does that exactly mean. I've tried reading through that 15 times and its still blowing way over my head. I copied and pasted the .gitattributes text and it seems to work. Don't know why, don't know how, just that it seems to somehow work again. Guess I got some reading to do about the gitattributes file. 

@Sembrani, I am free to do some testing if you can give me instructions.

**Comment by dodekeract** [comment]
@AetherV as far as I understand, Git thinks your .png files should be treated like text, aka - when you push the file, all `0x0A` (Line feed) bytes get converted to `0x0D` (Carriage return) + `0x0A` (Line feed). This was setup because Windows is weird and needs CRLF to mark line endings, while most other OS just use Line Feed.

Converting either from CRLF to LF or from LF to CRLF (which this repository does afaik) **will** break binary files because `0x0A` and `0x0D` + `0x0A` are no special characters in binary files, they are only meaningful in text files, which means the resulting files are complete nonsense.

**Comment by AetherV** [comment]
Good to know. Never heard of that problem, but it seems to kinda make sense to me. Thanks for the explanation :+1:

**Comment by Sembrani** [comment]
@dodekeract The .png should be set as binary so that git does not modify them, even through CRLF conversion. Looking at the current [.gitattributes](https://github.com/loopuleasa/Dota2-TheCore-Config-Engine/blob/master/.gitattributes) file, there is no `*.png binary` line? Perhaps this should be added.
