### ISSUE TITLE
Dota 2 Reborn Thread

### ISSUE THREAD

**Issue by loopuleasa** [loopuleasa/Dota2-TheCore-Config-Engine#17]
Discuss any issues and solutions here.
Haven't tested anything yet.

**Comment by loopuleasa** [comment]
Autoexec location is different.
Try copying the folders to C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\cfg

**Comment by LPiner** [comment]
Looks like the unborn stuff is saved in C:\Program Files (x86)\Steam\SteamApps\common\dota 2 beta\game\dota\cfg

Totally different format =(

**Comment by lawli3t** [comment]
im really sad, dont event want to play cuz of this 

doesnt work in new location for me either - even when renaming to vcfg

**Comment by SkipKayhil** [comment]
Alright, here's what I got so far:

[This should fix the autoexec not executing at all](https://www.reddit.com/r/DotA2/comments/3a7vcw/does_anyone_know_where_to_place_autoexeccfg_for/csa3em5) console output has changed so I can't confirm it executes on launch but I can type autoexec in console and I know its running

I run a modified version of your script but [most of these errors will be the same](https://puu.sh/it4pu/66ac289eb8.png)

and here's the list of broken commands:
* echo
* con_enable
* contimes
* execifexists
* snd_updateaudiocache (new sounds engine so this might not be needed anyway?)
* net_graphheight
* a bunch more net graph commands (apparently they took out the netgraph for some reason)
* r_threaded_shadow_clip
* r_queued_decals
* r_queued_postprocessing
* mat_queue_mode (deprecated?)
* cl_threaded_bone_setup
* cl_threaded_init

Again, these may not all necessarily be in your script but this is what I have so far. The most important one to find a replacement for is execifexists because it's kinda the backbone for all the keybinds

**Comment by xackoff** [comment]
all sixense commands are broken, no way to do right/left click from console. here is the dump of all Reborn cvars/commands - https://paste.ee/r/wak2Q

**Comment by loopuleasa** [comment]
Thank you guys for the help, I will try to look into it today.

And yeah, these commands have been removed:
echo
execifexists
playuisound

**Comment by loopuleasa** [comment]
Interested in commands to:
- issue left/right clicks
- play UI sounds
- print stuff on screen
- echo stuff in console
- bind stuff to alt and space

That's what I need to put the cfg engine back in shape.

**Comment by SkipKayhil** [comment]
is binding to alt and space broken? or just execifexists?

**Comment by xackoff** [comment]
Have been tinkering with new engine for hours, that's what I have found:

* issue left/right clicks - impossible
* play UI sounds - ```playsound``` works with direct pathing to sound files from ```\dota 2 beta\game\dota_imported\pak01_dir.vpk```, like this ```playsound sounds/ui/coins_big.vsnd_c```
* print stuff on screen - impossible
* echo stuff in console - impossible
* bind stuff to alt and space - space works as usual, alt should work with ```dota_remap_alt_key```, but I haven't tested this.

**Comment by loopuleasa** [comment]
Will test now. I heard it is.

**Comment by Sembrani** [comment]
Would it be possible to issue equivalent left/right clicks through steam controller support, simulating button presses on the controller?

**Comment by loopuleasa** [comment]
If you can tell me which command launches, I could do it.
Almost finished polishing the entire config to D2Reborn, but I cannot make left clicks to work.

**Comment by loopuleasa** [comment]
Some nice commands in source 2 I didn't know existed:

 
//Option to auto repeat right mouse
dota_player_auto_repeat_right_mouse 1 

//Allow alt+right click to force movement in a direction.
dota_unit_allow_moveto_direction 1

**Comment by loopuleasa** [comment]
Anyone know how I can make autoexec runnable at game start?

**Comment by xackoff** [comment]
Modify ```\dota 2 beta\game\dota\cfggame_convars.vcfg```, so it looks like this:

    "config"
    {
    	"convars"
    	{
    		"cl_updaterate"		"30"
    		"mat_motion_blur_enabled"	"0"
    		"snd_foliage_db_loss"	"0"
    		"exec"	"autoexec.cfg"
    	}
    }

**Comment by loopuleasa** [comment]
It is done!

**Comment by ybtyklstybtyklst** [comment]
line 73 in both reborn's dota2_functions_active.cfg and in the old one goes

alias "quick_upgrade_courier" "dota_shop_force_hotkeys 1;toggleshoppanel;shop_nav_to_tab 0;shop_select_itemrow 8;toggleshoppanel"

It should be 

alias "quick_upgrade_courier" "dota_shop_force_hotkeys 1;toggleshoppanel;shop_nav_to_tab 0;shop_select_itemrow 9;toggleshoppanel"

Since the courier and the upgrade have been moved in 6.84

net_graph is still included in functions but doesn't work any more in reborn

Installation instructions talk about rightclicking to clear keybinds - this only works in old client but clearing them in the old one also clears them in reborn.

**Comment by lawli3t** [comment]
I have found out that on my keyboard i can unbind Hotkeys when i press the "-"-key. I have a qwertz-layout though as im german. Maybe try that?

**Comment by loopuleasa** [comment]
Reborn Updates can be viewed here:
http://www.dota2.com/reborn/updates

New update added a wider variety of available key binds (most notably CTRL and SHIFT can be bound now, and they retain their old functions)

**Comment by loopuleasa** [comment]
Yeah, I posted a [**rant**](http://www.reddit.com/r/DotA2/comments/3at6vf/rant_config_guy_here_valve_can_we_please_get_full/) on reddit

**Comment by loopuleasa** [comment]
Recent update added this:

- Added a new simple network information overlay option that can display FPS, ping, and packet loss when in-game

**Comment by SkipKayhil** [comment]
NEW UPDATE NEED TO TEST THIS OUT I'M HYPED RN:
- Added an option for "Quick Attack" in settings (replaces some deprecated console commands from Source 1)

https://www.dota2.com/reborn/updates#June26

**Comment by Sembrani** [comment]
The question now is what alias do we bind the key to in the config file?

**Comment by SkipKayhil** [comment]
I'm not convinced it changed. You just tick the setting and I think it works. will confirm this

**Comment by loopuleasa** [comment]
HYYYYPE

**Comment by loopuleasa** [comment]
What is the command for quick attack?

Is it the old mc_attack?

**Comment by loopuleasa** [comment]
The command is 
    dota_settings_quick_target_attack 1

Enable it to 1 and 0 and mc_attack will change.

**Comment by Yackback** [comment]
Trying to create my own hotkeys, having trouble unbinding all of my keys in Reborn, far away key isn't working.

**Comment by loopuleasa** [comment]
If you press a far away key each time it works.
