### ISSUE TITLE
Newlines requested at line ends, for notepad viewing

### ISSUE THREAD

**Issue by loopuleasa** [loopuleasa/Dota2-TheCore-Config-Engine#37]
People reported that opening with notepad produces this:
[Notepad](http://i.imgur.com/c79uf0t.png) vs [Sublime Text](http://i.imgur.com/yqUhWVm.png)

To make it more noob friendly, I would love it if someone could add newlines at the end of each file. Maybe a program that does that exists?

**Comment by Ranguvar** [comment]
Yep, look for a Unix to Windows text converter.

**Comment by Sembrani** [comment]
Unfortunately, after some research, Git appears to automatically change newlines to LF (Unix), instead of CR+LF (Windows), so anything that is downloaded from GitHub will not open well in Notepad, or other text editors that rely on CR+LF.

Alternative Text Editors (ordered least complex -> most complex):
Notepad++
Atom.io
Sublime Text
Vim
GNU Emacs

**Comment by loopuleasa** [comment]
Good to know.

I did understand the difference between newline formats of the two systems (One with a carriage return and one without).

I should just place in the readme at the first line something like "BEST VIEWED WITH NOTEPAD++"

**Comment by Sembrani** [comment]
Yep, no worries, included the explanation for anyone else who comes across the same problem looking for an explanation.
